# might want to eventually replace this with some other file type
# https://martin-thoma.com/configuration-files-in-python/

mysql:
  DB_USER: root
  DB_PASS: B4Nqi68k19megKGd
  DB_HOSTNAME: 34.133.165.86
  DB_PORT: 3306
  DB_NAME: mysql_test_db
  RAW_DATA_DB_NAME: raw_data 
  DERIVED_DATA_DB_NAME: derived_data
alphavantage:
  API_KEY: FLS6AFYRTY2HHKHW
  PREMIUM_API_KEY: L7F2EVPKMZ3ZVJFQ

## alpha_vantage_api_key = 'FLS6AFYRTY2HHKHW' -- OLD key
## alpha_vantage_api_key = 'L7F2EVPKMZ3ZVJFQ' #Your premium API key for 75 API calls per minute is: L7F2EVPKMZ3ZVJFQ
